source("../R/LaTeXDatax.r")
library(testthat)
library(readr)
datax("data.tex",
      a = 1.2345678901234567890,
      b = 3,
      c = list(3e8, "m/s"),
      d = "hello",
      e = list(0.6122, "\\micro\\meter", "%.2g"),
      format = "%.4g"
)
str = read_file("data.tex")
test_that("data file", {
expect_equal(str,
"% Data file generated by LaTeXDatax.r
% Do not edit, may be overwritten!
\\pgfkeyssetvalue{/datax/a}{\\num{1.235}}
\\pgfkeyssetvalue{/datax/b}{\\num{3}}
\\pgfkeyssetvalue{/datax/c}{\\qty{3e+08}{m/s}}
\\pgfkeyssetvalue{/datax/d}{hello}
\\pgfkeyssetvalue{/datax/e}{\\qty{0.61}{\\micro\\meter}}
")
})

